# 02 - Preprocessing

In [ ]:
import pandas as pd
import os
import sys
sys.path.append('..')

from src.data.dataset import masks_to_polygons_dataset,split_dataset
from src.utils.polygon_preprocessing import convert_to_yolo_segmentation

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [2]:
images_path = '../data/raw/images'
masks_path  = '../data/raw/masks'
stage_1_path  = '../data/processed/Stage-1'
stage_2_path  = '../data/processed/Stage-2'

df = pd.read_csv('../data/raw/metadata.csv')

In [3]:
nv_df = df[df['dx'] == 'nv'].sample(3000)

nv_indices = [idx for idx in range(len(df)) if df.iloc[idx]['dx'] == 'nv']

# stage 2 excludes melanoma cases, so we filter them out before extracting polygons again
mel_indices = [idx for idx in range(len(df)) if df.iloc[idx]['dx'] == 'mel']

df_stage1 = df.drop(nv_indices)
df_stage2 = df.drop(mel_indices)

df_stage1 = pd.concat([df_stage1,nv_df])

df_stage1.reset_index(drop=True,inplace=True)
df_stage2.reset_index(drop=True,inplace=True)

In [4]:
df_stage1 = masks_to_polygons_dataset(masks_path, df, 'dx', stage=1, epsilon_threshold=0.01)

df_stage1['dx'] = df_stage1['class_id'].apply(lambda x: 'mel' if x[0] else 'not_mel')
df_stage1.head()

WARNING: CONTOUR LENTGH IS 2 in ISIC_0026769, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0029147, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0030276, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025867, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 1 in ISIC_0029062, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0028496, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025297, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025297, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0029776, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0029474, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0029474, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024893, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024477, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024997, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024761, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024761, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024910, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024910, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024851, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024871, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025066, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0030700, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024786, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024786, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0027392, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0028622, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024814, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025710, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025005, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0033391, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031253, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024850, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024850, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031558, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025131, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025223, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025903, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024545, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024400, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024853, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0032187, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0028655, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0033526, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0030150, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024930, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024999, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024552, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031666, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0027561, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0029591, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025248, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025248, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0027071, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0029780, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025543, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0030929, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024739, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025102, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024848, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024452, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024897, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024897, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024743, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024787, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031986, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024829, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024979, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025095, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025056, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0026520, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025256, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025080, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024379, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024510, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025109, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025162, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025119, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025119, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024362, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0030916, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025135, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025125, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025259, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024388, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024769, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024629, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025853, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0026662, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025111, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024801, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025282, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024878, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024878, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025269, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025572, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024541, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025646, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024750, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025012, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025022, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025690, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024852, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0026059, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024894, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025308, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025008, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025008, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024608, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0026210, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024458, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0026705, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024674, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025133, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025133, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025133, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025133, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025240, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025231, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025170, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025047, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0032028, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0032028, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024514, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024380, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024377, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025253, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025101, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031359, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024843, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0030076, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0029811, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024771, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025089, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0029371, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0029210, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031578, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025247, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025029, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0028941, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0026857, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
===================================
Max Value: 50
Min Value: 8
Mean: 23.105708877154527
Empty polygons: 0 / 10015

,lesion_id,image_id,dx,dx_type,class_id,polygons
0,HAM_0000118,ISIC_0027419,not_mel,histo,[0],"[[0.35833332, 0.09555556, 0.34833333, 0.306666..."
1,HAM_0000118,ISIC_0025030,not_mel,histo,[0],"[[0.51, 0.24222222, 0.42166665, 0.32222223, 0...."
2,HAM_0002730,ISIC_0026769,not_mel,histo,[0],"[[0.365, 0.12666667, 0.31166667, 0.19111112, 0..."
3,HAM_0002730,ISIC_0025661,not_mel,histo,[0],"[[0.47, 0.22, 0.41666666, 0.2888889, 0.4133333..."
4,HAM_0001466,ISIC_0031633,not_mel,histo,[0],"[[0.18166667, 0.13777778, 0.13833334, 0.271111..."

In [5]:
df_stage2 = masks_to_polygons_dataset(masks_path, df_stage2, 'dx', stage=2, epsilon_threshold=0.01)
df_stage2.head()

WARNING: CONTOUR LENTGH IS 2 in ISIC_0026769, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0029147, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0030276, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025867, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 1 in ISIC_0029062, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0028496, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025297, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025297, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0029776, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0029474, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0029474, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024893, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024477, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024997, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024761, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024761, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024910, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024910, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024851, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024871, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025066, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0030700, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024786, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024786, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0027392, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0028622, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024814, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025710, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025005, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0033391, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031253, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024850, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024850, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031558, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025131, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025223, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025903, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025102, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024848, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024452, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024897, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024897, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024743, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024787, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031986, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024829, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024979, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025095, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025056, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0026520, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025256, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025080, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024379, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024510, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025109, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025162, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025119, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025119, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024362, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0030916, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025135, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025125, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025259, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024388, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024769, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024629, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025853, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0026662, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025111, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024801, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025282, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024878, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024878, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025269, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025572, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024541, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025646, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0024750, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025012, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025022, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025690, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024852, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0026059, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0024894, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025308, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025008, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025008, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024608, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0026210, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024458, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0026705, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024674, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025133, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025133, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025133, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025133, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025240, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025231, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025170, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0025047, WILL BE SKIPPED
WARNING: CONTOUR LENTGH IS 2 in ISIC_0032028, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0032028, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024514, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024380, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024377, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025253, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025101, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031359, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024843, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0030076, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 2 in ISIC_0029811, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0024771, TRYING TO FIX...
  - Fixed Successfully!
WARNING: CONTOUR LENTGH IS 1 in ISIC_0025089, WILL BE SKIPPED
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0029371, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0029210, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0031578, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025247, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0025029, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0028941, TRYING TO FIX...
  - Fixed Successfully!
WARNING: THIS POLYGON IS NOT VALID IN THIS IMAGE ID: ISIC_0026857, TRYING TO FIX...
Recovered largest part from MultiPolygon
  - Fixed Successfully!
===================================
Max Value: 48
Min Value: 8
Mean: 22.88794262662483
Empty polygons: 0 / 8902

,lesion_id,image_id,dx,dx_type,class_id,polygons
0,HAM_0000118,ISIC_0027419,bkl,histo,[0],"[[0.35833332, 0.09555556, 0.34833333, 0.306666..."
1,HAM_0000118,ISIC_0025030,bkl,histo,[0],"[[0.51, 0.24222222, 0.42166665, 0.32222223, 0...."
2,HAM_0002730,ISIC_0026769,bkl,histo,[0],"[[0.365, 0.12666667, 0.31166667, 0.19111112, 0..."
3,HAM_0002730,ISIC_0025661,bkl,histo,[0],"[[0.47, 0.22, 0.41666666, 0.2888889, 0.4133333..."
4,HAM_0001466,ISIC_0031633,bkl,histo,[0],"[[0.18166667, 0.13777778, 0.13833334, 0.271111..."

In [6]:
df_stage1['dx'].value_counts()

dx
not_mel    8902
mel        1113
Name: count, dtype: int64

In [7]:
df_stage2['dx'].value_counts()

dx
nv       6705
bkl      1099
bcc       514
akiec     327
vasc      142
df        115
Name: count, dtype: int64

In [8]:
s1_train_df, s1_val_df , s1_test_df = split_dataset(df_stage1, 'dx', test_size=0.15, apply_leakage_check=True)

Train Patient ID : 6349
Val Patient ID   : 560
Test Patient ID  : 561

Train Images : 8508
Val Images   : 736
Test Images  : 771

Perfect! No Data Leakage Found.

In [9]:
s2_train_df, s2_val_df , s2_test_df = split_dataset(df_stage2, 'dx', test_size=0.15, apply_leakage_check=True)

Train Patient ID : 5827
Val Patient ID   : 512
Test Patient ID  : 517

Train Images : 7548
Val Images   : 660
Test Images  : 694

Perfect! No Data Leakage Found.

In [10]:
s1_train_df.to_pickle(os.path.join(stage_1_path,'train_df_splitted.pkl'))
s1_val_df.to_pickle(os.path.join(stage_1_path,'valid_df_splitted.pkl'))
s1_test_df.to_pickle(os.path.join(stage_1_path,'test_df_splitted.pkl'))

In [11]:
s2_train_df.to_pickle(os.path.join(stage_2_path,'train_df_splitted.pkl'))
s2_val_df.to_pickle(os.path.join(stage_2_path,'valid_df_splitted.pkl'))
s2_test_df.to_pickle(os.path.join(stage_2_path,'test_df_splitted.pkl'))

In [12]:
convert_to_yolo_segmentation(images_path,stage_1_path,s1_train_df,s1_val_df,s1_test_df)

train Is Processing Now...: 100%|██████████| 8508/8508 [00:25<00:00, 333.19it/s]

train Done!

val Is Processing Now...: 100%|██████████| 736/736 [00:03<00:00, 207.92it/s]

val Done!

test Is Processing Now...: 100%|██████████| 771/771 [00:03<00:00, 221.11it/s]

test Done!

In [13]:
convert_to_yolo_segmentation(images_path,stage_2_path,s2_train_df,s2_val_df,s2_test_df)

train Is Processing Now...: 100%|██████████| 7548/7548 [00:35<00:00, 215.44it/s]

train Done!

val Is Processing Now...: 100%|██████████| 660/660 [00:04<00:00, 147.54it/s]

val Done!

test Is Processing Now...: 100%|██████████| 694/694 [00:04<00:00, 164.08it/s]

test Done!